name: Build Server
on:
  push:
    branches: [master]
  pull_request:

jobs:
  server-build:
    name: 'Build Auth'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout: 'app/server'
          sparse-checkout-cone-mode: false

      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x

      - name: Build
        run: deno task build